#GENERAL
timeonload: true

tasks:
  command_time:
    commands:
      - say This message will only show up at a specific time.
    time:
      - "13:49:00" # Use HH:mm:ss for real life time and HH:mm for minecraft time (useMinecraftTime: true)
    gender: console
  command_minecraft_time:
    commands:
      - say This message will only show at a specific minecraft time
    time:
      - "15:00"
    gender: console
    useMinecraftTime: true
  random_test_command:
    commands:
      - say This message appears every 10 seconds with a chance of 50%
    seconds: 10
    gender: console
    random: 0.5
    perUser: true
  world_limited_command:
    commands:
      - say This command will only run on the main world and on Monday, Wednesday and Sunday
      - say This command will be executed sometimes as well
    seconds: 5
    days:
      - MONDAY
      - WEDNESDAY
      - SUNDAY
    worlds:
      - world
    gender: console
  only_executes_5_times:
    commands:
      - say This command will only be executed 5 times
    seconds: 3
    gender: console
    executionLimit: 5