main: me.playbosswar.com.Main
name: "${project.name}"
version: "${project.version}"
description: "${project.description}"
author: PlayBossWar
softdepend:
  - PlaceholderAPI

commands:
  commandtimer:
    usage: /<command>
    aliases: [cmt]
    description: List all commands